# Site
repository: theo-ng/theo-ng.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Theodore Ng
title: Full Stack Software Engineer
email: theodore_ng@hotmail.com

# Social links
github_username:  theo-ng
linkedin_username: theo-ng-79560640

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  > "Outspoken with a quirky sense of humour. Committed to delivering high quality work and striving for excellence. I like to get to the root of a problem and solve the root cause rather than band-aid the symptoms. Good with articulating solutions to others and being user-focused with an eye for design and aesthetics."

# More Section
more_title: Technical Summary #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  - **Languages​**: JavaScript, Ruby, ​HTML5, CSS/SCSS, SQL
  - **Methodologies**: ​Agile, Scrum, TDD, XP
  - **Tools**: ​Git, JIRA, Visual Studio, Eclipse, Visual Studio Code
  - **Frameworks​**: hapi.js, Express, React, Redux, Ruby on Rails

# Experience Section
# experience_title: Professional Experience #(Use this to override about experience section title)

# Projects Section
# projects_title: Technical Projects #(Use this to override about projects section title)

# Education Section
# education_title: Education #(Use this to override about education section title)


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
